### PR TITLE
Art Asset folder and Note added

### PR DESCRIPTION
**Pull request by Jlancy**

### CODE REVIEW

**Comment by ddeleon1219** [comment]
here is an update of the items, buildings and ground textiles
item-sheet

**Comment by PhilTanw** [comment]
I think the next things we will need are inanimate object, foliage, doodad, etc. So like trees, rocks, mechanism such as weight sensors or level, maybe the boulder, and possibly any kind of a modifier for the tile to make them appear differently (essentially, a design that would be placed above the tile). We don't necessarily need everything in one go. If anything, just the trees, rocks, and tile modifiers would be a good start.

**Comment by ddeleon1219** [comment]
OK I am making note of it, I will compile another sheet with the new items and designs that have been requested as well as the last items that i am missing for the item list. Thank you for updating me and if you have anymore request please feel free to leave a comment so I can add the new request to my todo list.

**Comment by PhilTanw** [comment]
Also, here are a few sample sprite sheets I made using what we have. There are some empty space in case there are more stuff to be added. The sheet can just be large enough to hold all the sprites since we can expand them whenever without complicating things with the programming. Eventually, I think it might be nice to have the items sprite sheet sorted based on the item ID.
dimasterrain
samplespritesheet
samplespritesheetwithguides

**Comment by PhilTanw** [comment]
Sorry for the double post but one more thing, here's a sample with the houses. I made the house a little transparent to help see the alignment.
samplespritesheetforlargeobjects

**Comment by ddeleon1219** [comment]
ground texture layout

I am still need to layout the trees i am finishing and the last 6 items i completed so far, I am also including the UI sketch i came up with 
ui sketch

**Comment by ddeleon1219** [comment]
My apologies for lagging it on some of the assets, last time i spoke with Justine he informed me that you guys needed the throne layout for the game, I am currently working on the layout as well as doing the items but I wanted to share the trees that I have made for the game as well as the throne sketch with some new sketches of the items. I am also redoing the houses they felt disconnected in comparison with the other items , animation and trees.Let me know what you guys think
kings throne
img_1869
img_1868

trees

**Comment by ddeleon1219** [comment]
Based on these colors I will have to fix some of the textile designs, mostly the grass ones

**Comment by PhilTanw** [comment]
For the sprite sheet, would you be able to remove the guide(orange box) on the background of the trees?

**Comment by ddeleon1219** [comment]
Hi Just want to get some input on the design, i also came across
2-screenshot__004
 this layout, please let me know if this is better.

**Comment by ddeleon1219** [comment]
trees
does this work better

**Comment by PhilTanw** [comment]
Yes, thank you.

**Comment by ddeleon1219** [comment]
If you guys need more stuff or for me to fix other texture send me a message I am free all day tomorrow, friday and the weekend.

**Comment by Jlancy** [comment]
Need to have the concept piece for the kickstarter banner. Please focus on that piece for now. Good work on the other things though. They fit in well with the rest.

Thanks,
Justin

Date: Mon, 11 Jan 2016 22:37:13 -0800

**Pull request merged**
